### PR TITLE
feat!: add idle_count_min` and `idle_scale_factor` to Docker Machine autoscaling options

### LINKED ISSUE #556: IdleScaleFactor
Is there any way to define `IdleScaleFactor`?
https://docs.gitlab.com/runner/configuration/autoscale.html#the-idlescalefactor-strategy

### PR DESCRIPTION
**Pull request by tmeijn**
## Description

Switches from hardcoded options to free-from scaling configuration. This reduces the module complexity by allowing to get rid of a number of variables while giving more control to the user to define their options without us having to build support into it for.

Adds `idle_scale_factor` and `idle_count_min` Docker Machine options. See [documentation](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnersmachine-section").

## Migrations required

YES - users will have to change the input name from `runners_machine_autoscaling` to `runners_machine_autoscaling_options`. No other changes should be needed, we just support _more_ options. A migration script is available.

## Verification

No input given:

(end of rendered `config.toml`)

image

Input:

```hcl

runners_machine_autoscaling_options = [
    {
      periods           = ["* * 9-17 * * mon-fri *", "* * 9-17 * * mon-fri *"]
      idle_count        = 50
      idle_count_min    = 10
      idle_time         = 3600
      timezone          = "UTC"
      idle_scale_factor = 1.5
    },
    {
      periods    = ["* * 9-17 * * mon-fri *", "* * 9-17 * * mon-fri *"]
      idle_count = 50
      idle_time  = 3600
      timezone   = "Europe/Amsterdam"
    }
  ]
```

Rendered `config.toml`:

image

Apply results:

image

Closes #556

### CODE REVIEW

**Comment by tmeijn** [comment]
Hey @npalm, @kayman-mk, this PR is totally not ready, but wanted to get yall's opinion on whether you think this is even an acceptable or desired direction to go in. Played around with it a bit and

image

Produces

image

and 

image

**Comment by npalm** [comment]
Can you set the PR in "draft" as long it is not ready?

**Comment by kayman-mk** [comment]
@tmeijn Could you please draft the changes to the input variables? There is another PR in the pipeline to restructure everything. Would be good to combine both.

See #723

**Comment by kayman-mk** [comment]
Makes sense to me to support the new settings. But I suggest to use `idle_count` instead of `IdleCount`, ... to have a consistent naming through out the module.

**Comment by tmeijn** [comment]
> Makes sense to me to support the new settings. But I suggest to use `idle_count` instead of `IdleCount`, ... to have a consistent naming through out the module.

Yeah this is because the naming convention in the `config.toml` is very inconsistent... but I was doubting between passing the keys as is or us providing the conversion.

**Comment by tmeijn** [comment]
@kayman-mk I was actually thinking to write a conversion from snake_case to TitleCase, sorry didn't make that intent clear in my previous comment. Do you think that would be better?

**Comment by kayman-mk** [comment]
I really appreciate such a converter, but I guess it complicates the code as there is no function available in Terraform. The related issue hashicorp/terraform#25230 is still open for a while.

I think it is better to leave the code as it is now and add some unit tests. Gosh, I have to get #632 ready now.

**Comment by tmeijn** [comment]
Hey @kayman-mk I just tried it, see https://github.com/cattle-ops/terraform-aws-gitlab-runner/pull/711/commits/c3cf08c002435807b4904489ae1e9e7242d9ecc8.

I personally don't find it too complex looking, but I'll let you decide what you would prefer based on this example.

**Comment by tmeijn** [comment]
@kayman-mk I think this PR is ready for review. I do not what's up with the `Lint PR title` action, are you able to help?

**Comment by kayman-mk** [comment]
@tmeijn KICS is reporting problems. Please fix them. Lint PR title: Works for me, I guess because I am a member of `cattle-ops`. Have to dig in a little bit further. Guess a PAT will help for forks outside the organization.

Could you please enhance [this script](https://github.com/tmeijn/terraform-aws-gitlab-runner/blob/feat/switch-to-free-form-scaling-config/migrations/migrate-to-7-0-0.sh) and a a conversion for your renaming?

**Comment by tmeijn** [comment]
@kayman-mk Regarding the KICS errors, I see you already fixed them in https://github.com/cattle-ops/terraform-aws-gitlab-runner/pull/755, so I think once that is merged the errors reported here will automatically resolve.

Regarding the PR lint: it did seem to work in my first contribution I made at least: https://github.com/cattle-ops/terraform-aws-gitlab-runner/pull/705/checks#step:2:1

**Comment by npalm** [comment]
The PR linter is failing since the fork have no access to the write token used in the workflow.

**Review by kayman-mk — APPROVED** [review]
Thanks for your work!

**Pull request merged**
