### PR TITLE
fix: retry the jq installation in case of errors

### PR DESCRIPTION
**Pull request by ryancausey**
## Description

In case of network connection problems, the `yum` operations ends with an error. This PR adds a retry to install `jq`.

## Migrations required

NO

## Verification

Confirmed this works for my setup by vendoring this module with these changes.

### CODE REVIEW

**Comment by kayman-mk** [comment]
Could you please share the error message you have seen in the logs?

**Comment by ryancausey** [comment]
> Could you please share the error message you have seen in the logs?

```bash
Nov  8 21:43:26 user-data:
Nov  8 21:43:26 user-data: Error downloading packages:
Nov  8 21:43:26 user-data:  jq-1.5-1.amzn2.0.2.x86_64: [Errno 256] No more mirrors to try.
Nov  8 21:43:26 user-data:
```

The added retry logic eventually retries this package install enough times to make it work. When it was a single try, this would fail causing the userdata script would fail and thus causing the runner to fail to register and start.

**Review by kayman-mk — CHANGES_REQUESTED** [review]

**Comment by kayman-mk** [comment]
Installing `jq` always shouldn't do any harm, but removes the `if`. Thought about integrating this into the loop above. But this seems to be a bit more tricky.

**Review by kayman-mk — APPROVED** [review]

**Comment by kayman-mk** [comment]
Thanks for fixing this issue, @ryancausey

**Pull request merged**
