### PR TITLE
feat!: update docker machine and encrypt all EBS

### PR DESCRIPTION
**Pull request by jonmcewen**
## Description

- updates the docker-machine to `0.16.2-gitlab.19-cki.5` to set the encryption key for the instances
- fleet: creates new instances with encrypted volumes

## Migrations required

This could be a breaking change as you might have to change the key policy for the encryption key to allow EBS to access the key.

```
       {
            "Sid": "Allow access through EBS for all principals in the account that are authorized to use EBS",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:CreateGrant",
                "kms:DescribeKey"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "kms:CallerAccount": "990563477234",
                    "kms:ViaService": "ec2.eu-central-1.amazonaws.com"
                }
            }
        }
```

## Verification

Manually tested the new version.

### CODE REVIEW

**Comment by kayman-mk** [comment]
https://gitlab.com/cki-project/mirror/docker-machine/-/commit/27ff34dcf7a67101c98fa978f63899aca36dc8aa

```
--amazonec2-volume-encrypted`: Encrypt Amazon EBS volume attached to the instance.
--amazonec2-volume-kms-key`: The KMS Key ID/ARN/Alias to be used to encrypt the volume.
```

**Comment by kayman-mk** [comment]
Great! I was already looking for that option but didn't find it.

As we have the KMS keys, ... available in the module, we should go a little further and pass them to the docker machine. Could you add this please to the PR, @jonmcewen?

**Comment by kayman-mk** [comment]
I guess we have to fix the key policy to allow spot instances.

**Review by kayman-mk — APPROVED** [review]

**Comment by jonmcewen** [comment]
Thanks @kayman-mk . Sorry I wasn't around to help finish this off

**Pull request merged**
