### PR TITLE
feat!: restructure module variables

### LINKED ISSUE #467: Add network_mode to docker.runner config
Some CI job require alter kernel parameters or access ec2 link local address. It could be helpful if we can use the host network.

[runner-config](https://docs.gitlab.com/runner/configuration/advanced-configuration.html)

### LINKED ISSUE #513: wait_for_services_timeout parameter not supported
Hello,

First, thank you very much for this very good module ! 
 
We search to increase [wait_for_services_timeout](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnersdocker-section) runner parameter but, it seems that this parameter is not implemented in the module.

Do you plan to develop it in the roadmap?

Best regards,
Geoffrey

### LINKED ISSUE #819: Breaking Change Ahead: Version 7
I will add some information on how to migrate to the new version in the next days. Still some time to go and not 100% discussed internally.

ToDo:
- [x] get an approval for #810 and then
- [x] test #723 

# Major Version 7

## Main reasons
  - harmonize the variable names
  - harmonize the documentation
  - remove deprecated variables
  - gain a better overview of the features provided
  - upgrade to Terraform 1.3+ for optional variables in maps

## Feature added
  - all possible Docker settings
  - `idle_scale_factor`

### PR DESCRIPTION
**Pull request by kayman-mk**
## Description

Restructures all input variables of the agent and executor.

Closes #467 (add network_mode to docker.runner config)
Closes #513 (wait_for_services_timeout paramete)
Closes #819

## Migrations required

YES. Check the script in `/migrations/migrate-to-7-0-0.sh`.

### CODE REVIEW

**Comment by tmeijn** [comment]
@kayman-mk another thing we could possibly deprecate and remove:

https://github.com/cattle-ops/terraform-aws-gitlab-runner/blob/297cd606729b666b6814b0a0484465a4e462cc68/locals.tf#L83-L93

I do not think we need to support Docker Machine < 0.16.2, which has been released ~3,5 years ago.

**Comment by tmeijn** [comment]
@kayman-mk https://github.com/cattle-ops/terraform-aws-gitlab-runner/issues/524#issuecomment-1211576537

Is this work you want to pick up in this iteration? Since we are doing a pretty extensive rewrite of variables already I think this is also a good one to introduce now..

**Comment by kayman-mk** [comment]
Should definately be done. See #575

**Comment by kayman-mk** [comment]
Testing with the current setup at Hapag-Lloyd:
a) Running the shell script to convert the module call
b) execute some jobs on the new module version

**Comment by kayman-mk** [comment]
Testing and bug fixing to be done in #860

**Comment by kayman-mk** [comment]
@npalm I am fine with version 7 now. Could you please have a look?

**Comment by npalm** [comment]
Will check this PR end of this week or early next week. Sorry for the delay.

**Comment by npalm** [comment]
@kayman-mk I assume I just deploy main, next upgrade to this branch and ran the migration. Anything I should take care of?

**Comment by kayman-mk** [comment]
@npalm Yeah, that's the way it should work.

**Review by npalm — CHANGES_REQUESTED** [review]
Checked the runner-default exampl. Was not able to upgrade. Created a fix in PR https://github.com/cattle-ops/terraform-aws-gitlab-runner/pull/905

**Pull request merged**
